apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
    autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "2"
  name: kube-whisperer
  namespace: default
spec:
  predictor:
    imagePullSecrets:
      - name: acr-secret
    containers:
    - env:
      - name: WHISPER_MODEL
        value: tiny
      - name: COMPUTE_TYPE
        value: float32
      - name: DEVICE
        value: "cuda"
      - name: CPU_THREADS
        value: "4"
      - name: NUM_WORKERS
        value: "2"
      - name: MAX_FILE_SIZE
        value: "26214400"
      - name: ENVIRONMENT
        value: "production"
      - name: XDG_CACHE_HOME
        value: "/tmp/whisper_cache"
      - name: MODEL_DOWNLOAD_ROOT
        value: "/tmp/whisper_cache/models"
      image: ghcr.io/bnallapeta/kube-whisperer:0.0.1 
      livenessProbe:
        httpGet:
          path: /live
          port: http1
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        httpGet:
          path: /ready
          port: http1
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      startupProbe:
        httpGet:
          path: /health
          port: http1
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 30
        failureThreshold: 12
        successThreshold: 1
      name: kserve-container
      ports:
      - containerPort: 8000
        name: http1
        protocol: TCP
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: temp
      - mountPath: /tmp/whisper_audio
        name: whisper-data
      - mountPath: /tmp/whisper_cache
        name: whisper-cache
      - mountPath: /tmp/whisper
        name: whisper-temp
    volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 1Gi
      name: temp
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: whisper-data
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: whisper-cache
    - emptyDir:
        medium: Memory
        sizeLimit: 1Gi
      name: whisper-temp
